<?php

return array (
  'database' => 
  array (
    'default_character_set_name' => 'latin1',
    'default_collation_name' => 'latin1_swedish_ci',
  ),
  'tables' => 
  array (
    'forum' => 
    array (
      'table' => 
      array (
        'table_name' => 'forum',
        'engine' => 'InnoDB',
        'table_comment' => '',
        'table_collation' => 'latin1_swedish_ci',
        'character_set_name' => 'latin1',
      ),
      'columns' => 
      array (
        'id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'forum',
          'COLUMN_NAME' => 'id',
          'ORDINAL_POSITION' => '1',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '10',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(8)',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => 'auto_increment',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
        'title' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'forum',
          'COLUMN_NAME' => 'title',
          'ORDINAL_POSITION' => '2',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => '64',
          'CHARACTER_OCTET_LENGTH' => '64',
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'latin1',
          'COLLATION_NAME' => 'latin1_swedish_ci',
          'COLUMN_TYPE' => 'varchar(64)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
        'description' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'forum',
          'COLUMN_NAME' => 'description',
          'ORDINAL_POSITION' => '3',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => '255',
          'CHARACTER_OCTET_LENGTH' => '255',
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'latin1',
          'COLLATION_NAME' => 'latin1_swedish_ci',
          'COLUMN_TYPE' => 'varchar(255)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
        'forum_category_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'forum',
          'COLUMN_NAME' => 'forum_category_id',
          'ORDINAL_POSITION' => '4',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '10',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(8)',
          'COLUMN_KEY' => 'MUL',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
        'minimum_access' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'forum',
          'COLUMN_NAME' => 'minimum_access',
          'ORDINAL_POSITION' => '5',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'enum',
          'CHARACTER_MAXIMUM_LENGTH' => '6',
          'CHARACTER_OCTET_LENGTH' => '6',
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'latin1',
          'COLLATION_NAME' => 'latin1_swedish_ci',
          'COLUMN_TYPE' => 'enum(\'member\',\'admin\',\'staff\',\'banned\')',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
      ),
      'indexes' => 
      array (
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 'forum',
            'Non_unique' => '0',
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => '1',
            'Column_name' => 'id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'forum_category_id' => 
        array (
          1 => 
          array (
            'Table' => 'forum',
            'Non_unique' => '1',
            'Key_name' => 'forum_category_id',
            'Seq_in_index' => '1',
            'Column_name' => 'forum_category_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => 'YES',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
        'forum_ibfk_1' => 
        array (
          'TABLE_NAME' => 'forum',
          'COLUMN_NAME' => 'forum_category_id',
          'CONSTRAINT_NAME' => 'forum_ibfk_1',
          'REFERENCED_TABLE_NAME' => 'forum_category',
          'REFERENCED_COLUMN_NAME' => 'id',
          'UPDATE_RULE' => 'NO ACTION',
          'DELETE_RULE' => 'SET NULL',
        ),
      ),
    ),
    'post' => 
    array (
      'table' => 
      array (
        'table_name' => 'post',
        'engine' => 'InnoDB',
        'table_comment' => '',
        'table_collation' => 'latin1_swedish_ci',
        'character_set_name' => 'latin1',
      ),
      'columns' => 
      array (
        'id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'post',
          'COLUMN_NAME' => 'id',
          'ORDINAL_POSITION' => '1',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '10',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => 'auto_increment',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
        'date_added' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'post',
          'COLUMN_NAME' => 'date_added',
          'ORDINAL_POSITION' => '2',
          'COLUMN_DEFAULT' => 'CURRENT_TIMESTAMP',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'timestamp',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => '0',
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'timestamp',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
        'user_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'post',
          'COLUMN_NAME' => 'user_id',
          'ORDINAL_POSITION' => '3',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '10',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => 'MUL',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
        'thread_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'post',
          'COLUMN_NAME' => 'thread_id',
          'ORDINAL_POSITION' => '4',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '10',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(8)',
          'COLUMN_KEY' => 'MUL',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
        'content' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'post',
          'COLUMN_NAME' => 'content',
          'ORDINAL_POSITION' => '5',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'text',
          'CHARACTER_MAXIMUM_LENGTH' => '65535',
          'CHARACTER_OCTET_LENGTH' => '65535',
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'latin1',
          'COLLATION_NAME' => 'latin1_swedish_ci',
          'COLUMN_TYPE' => 'text',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
        'last_updated' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'post',
          'COLUMN_NAME' => 'last_updated',
          'ORDINAL_POSITION' => '6',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'timestamp',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => '0',
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'timestamp',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
      ),
      'indexes' => 
      array (
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 'post',
            'Non_unique' => '0',
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => '1',
            'Column_name' => 'id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'user_id' => 
        array (
          1 => 
          array (
            'Table' => 'post',
            'Non_unique' => '1',
            'Key_name' => 'user_id',
            'Seq_in_index' => '1',
            'Column_name' => 'user_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'thread_id' => 
        array (
          1 => 
          array (
            'Table' => 'post',
            'Non_unique' => '1',
            'Key_name' => 'thread_id',
            'Seq_in_index' => '1',
            'Column_name' => 'thread_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
        'post_ibfk_3' => 
        array (
          'TABLE_NAME' => 'post',
          'COLUMN_NAME' => 'user_id',
          'CONSTRAINT_NAME' => 'post_ibfk_3',
          'REFERENCED_TABLE_NAME' => 'user',
          'REFERENCED_COLUMN_NAME' => 'user_id',
          'UPDATE_RULE' => 'NO ACTION',
          'DELETE_RULE' => 'CASCADE',
        ),
        'post_ibfk_4' => 
        array (
          'TABLE_NAME' => 'post',
          'COLUMN_NAME' => 'thread_id',
          'CONSTRAINT_NAME' => 'post_ibfk_4',
          'REFERENCED_TABLE_NAME' => 'thread',
          'REFERENCED_COLUMN_NAME' => 'id',
          'UPDATE_RULE' => 'NO ACTION',
          'DELETE_RULE' => 'CASCADE',
        ),
      ),
    ),
    'thread' => 
    array (
      'table' => 
      array (
        'table_name' => 'thread',
        'engine' => 'InnoDB',
        'table_comment' => '',
        'table_collation' => 'latin1_swedish_ci',
        'character_set_name' => 'latin1',
      ),
      'columns' => 
      array (
        'id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'thread',
          'COLUMN_NAME' => 'id',
          'ORDINAL_POSITION' => '1',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '10',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(8)',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => 'auto_increment',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
        'title' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'thread',
          'COLUMN_NAME' => 'title',
          'ORDINAL_POSITION' => '2',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => '96',
          'CHARACTER_OCTET_LENGTH' => '96',
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'latin1',
          'COLLATION_NAME' => 'latin1_swedish_ci',
          'COLUMN_TYPE' => 'varchar(96)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
        'date_added' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'thread',
          'COLUMN_NAME' => 'date_added',
          'ORDINAL_POSITION' => '3',
          'COLUMN_DEFAULT' => 'CURRENT_TIMESTAMP',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'timestamp',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => '0',
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'timestamp',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
        'user_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'thread',
          'COLUMN_NAME' => 'user_id',
          'ORDINAL_POSITION' => '4',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '10',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => 'MUL',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
        'forum_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'thread',
          'COLUMN_NAME' => 'forum_id',
          'ORDINAL_POSITION' => '5',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '10',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(8)',
          'COLUMN_KEY' => 'MUL',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
        'view_count' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'thread',
          'COLUMN_NAME' => 'view_count',
          'ORDINAL_POSITION' => '6',
          'COLUMN_DEFAULT' => '0',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '10',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
        'date_updated' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'thread',
          'COLUMN_NAME' => 'date_updated',
          'ORDINAL_POSITION' => '7',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'datetime',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => '0',
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'datetime',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
        'sticky' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'thread',
          'COLUMN_NAME' => 'sticky',
          'ORDINAL_POSITION' => '8',
          'COLUMN_DEFAULT' => '0',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'tinyint',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '3',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'tinyint(4)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
        'deleted' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'thread',
          'COLUMN_NAME' => 'deleted',
          'ORDINAL_POSITION' => '9',
          'COLUMN_DEFAULT' => '0',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'tinyint',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '3',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'tinyint(4)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
      ),
      'indexes' => 
      array (
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 'thread',
            'Non_unique' => '0',
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => '1',
            'Column_name' => 'id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'forum_id' => 
        array (
          1 => 
          array (
            'Table' => 'thread',
            'Non_unique' => '1',
            'Key_name' => 'forum_id',
            'Seq_in_index' => '1',
            'Column_name' => 'forum_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'user_id' => 
        array (
          1 => 
          array (
            'Table' => 'thread',
            'Non_unique' => '1',
            'Key_name' => 'user_id',
            'Seq_in_index' => '1',
            'Column_name' => 'user_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => 'YES',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
        'thread_ibfk_4' => 
        array (
          'TABLE_NAME' => 'thread',
          'COLUMN_NAME' => 'user_id',
          'CONSTRAINT_NAME' => 'thread_ibfk_4',
          'REFERENCED_TABLE_NAME' => 'user',
          'REFERENCED_COLUMN_NAME' => 'user_id',
          'UPDATE_RULE' => 'NO ACTION',
          'DELETE_RULE' => 'CASCADE',
        ),
        'thread_ibfk_5' => 
        array (
          'TABLE_NAME' => 'thread',
          'COLUMN_NAME' => 'forum_id',
          'CONSTRAINT_NAME' => 'thread_ibfk_5',
          'REFERENCED_TABLE_NAME' => 'forum',
          'REFERENCED_COLUMN_NAME' => 'id',
          'UPDATE_RULE' => 'NO ACTION',
          'DELETE_RULE' => 'CASCADE',
        ),
      ),
    ),
    'phinxlog' => 
    array (
      'table' => 
      array (
        'table_name' => 'phinxlog',
        'engine' => 'InnoDB',
        'table_comment' => '',
        'table_collation' => 'utf8_general_ci',
        'character_set_name' => 'utf8',
      ),
      'columns' => 
      array (
        'version' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'phinxlog',
          'COLUMN_NAME' => 'version',
          'ORDINAL_POSITION' => '1',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'bigint',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '19',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'bigint(20)',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
        'migration_name' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'phinxlog',
          'COLUMN_NAME' => 'migration_name',
          'ORDINAL_POSITION' => '2',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => '100',
          'CHARACTER_OCTET_LENGTH' => '300',
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8',
          'COLLATION_NAME' => 'utf8_general_ci',
          'COLUMN_TYPE' => 'varchar(100)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
        'start_time' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'phinxlog',
          'COLUMN_NAME' => 'start_time',
          'ORDINAL_POSITION' => '3',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'timestamp',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => '0',
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'timestamp',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
        'end_time' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'phinxlog',
          'COLUMN_NAME' => 'end_time',
          'ORDINAL_POSITION' => '4',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'timestamp',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => '0',
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'timestamp',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
        'breakpoint' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'phinxlog',
          'COLUMN_NAME' => 'breakpoint',
          'ORDINAL_POSITION' => '5',
          'COLUMN_DEFAULT' => '0',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'tinyint',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '3',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'tinyint(1)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
      ),
      'indexes' => 
      array (
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 'phinxlog',
            'Non_unique' => '0',
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => '1',
            'Column_name' => 'version',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => NULL,
    ),
    'forum_category' => 
    array (
      'table' => 
      array (
        'table_name' => 'forum_category',
        'engine' => 'InnoDB',
        'table_comment' => '',
        'table_collation' => 'utf8_unicode_ci',
        'character_set_name' => 'utf8',
      ),
      'columns' => 
      array (
        'id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'forum_category',
          'COLUMN_NAME' => 'id',
          'ORDINAL_POSITION' => '1',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '10',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(8)',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => 'auto_increment',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
        'category' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'forum_category',
          'COLUMN_NAME' => 'category',
          'ORDINAL_POSITION' => '2',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'char',
          'CHARACTER_MAXIMUM_LENGTH' => '64',
          'CHARACTER_OCTET_LENGTH' => '192',
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8',
          'COLLATION_NAME' => 'utf8_unicode_ci',
          'COLUMN_TYPE' => 'char(64)',
          'COLUMN_KEY' => 'UNI',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
      ),
      'indexes' => 
      array (
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 'forum_category',
            'Non_unique' => '0',
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => '1',
            'Column_name' => 'id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'category' => 
        array (
          1 => 
          array (
            'Table' => 'forum_category',
            'Non_unique' => '0',
            'Key_name' => 'category',
            'Seq_in_index' => '1',
            'Column_name' => 'category',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => NULL,
    ),
    'static_email_content' => 
    array (
      'table' => 
      array (
        'table_name' => 'static_email_content',
        'engine' => 'InnoDB',
        'table_comment' => '',
        'table_collation' => 'utf8_unicode_ci',
        'character_set_name' => 'utf8',
      ),
      'columns' => 
      array (
        'id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'static_email_content',
          'COLUMN_NAME' => 'id',
          'ORDINAL_POSITION' => '1',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '10',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => 'auto_increment',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
        'type' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'static_email_content',
          'COLUMN_NAME' => 'type',
          'ORDINAL_POSITION' => '2',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'enum',
          'CHARACTER_MAXIMUM_LENGTH' => '14',
          'CHARACTER_OCTET_LENGTH' => '42',
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8',
          'COLLATION_NAME' => 'utf8_unicode_ci',
          'COLUMN_TYPE' => 'enum(\'reset_password\',\'food_order\')',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
        'content' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'static_email_content',
          'COLUMN_NAME' => 'content',
          'ORDINAL_POSITION' => '3',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'text',
          'CHARACTER_MAXIMUM_LENGTH' => '65535',
          'CHARACTER_OCTET_LENGTH' => '65535',
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8',
          'COLLATION_NAME' => 'utf8_unicode_ci',
          'COLUMN_TYPE' => 'text',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
      ),
      'indexes' => 
      array (
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 'static_email_content',
            'Non_unique' => '0',
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => '1',
            'Column_name' => 'id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => NULL,
    ),
    'user' => 
    array (
      'table' => 
      array (
        'table_name' => 'user',
        'engine' => 'InnoDB',
        'table_comment' => '',
        'table_collation' => 'utf8_unicode_ci',
        'character_set_name' => 'utf8',
      ),
      'columns' => 
      array (
        'user_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'user',
          'COLUMN_NAME' => 'user_id',
          'ORDINAL_POSITION' => '1',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '10',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => 'auto_increment',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
        'username' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'user',
          'COLUMN_NAME' => 'username',
          'ORDINAL_POSITION' => '2',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => '255',
          'CHARACTER_OCTET_LENGTH' => '765',
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8',
          'COLLATION_NAME' => 'utf8_unicode_ci',
          'COLUMN_TYPE' => 'varchar(255)',
          'COLUMN_KEY' => 'UNI',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
        'email' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'user',
          'COLUMN_NAME' => 'email',
          'ORDINAL_POSITION' => '3',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => '255',
          'CHARACTER_OCTET_LENGTH' => '765',
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8',
          'COLLATION_NAME' => 'utf8_unicode_ci',
          'COLUMN_TYPE' => 'varchar(255)',
          'COLUMN_KEY' => 'UNI',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
        'display_name' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'user',
          'COLUMN_NAME' => 'display_name',
          'ORDINAL_POSITION' => '4',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => '50',
          'CHARACTER_OCTET_LENGTH' => '150',
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8',
          'COLLATION_NAME' => 'utf8_unicode_ci',
          'COLUMN_TYPE' => 'varchar(50)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
        'password' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'user',
          'COLUMN_NAME' => 'password',
          'ORDINAL_POSITION' => '5',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => '128',
          'CHARACTER_OCTET_LENGTH' => '384',
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8',
          'COLLATION_NAME' => 'utf8_unicode_ci',
          'COLUMN_TYPE' => 'varchar(128)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
        'date_joined' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'user',
          'COLUMN_NAME' => 'date_joined',
          'ORDINAL_POSITION' => '6',
          'COLUMN_DEFAULT' => 'CURRENT_TIMESTAMP',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'timestamp',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => '0',
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'timestamp',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
        'role' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'user',
          'COLUMN_NAME' => 'role',
          'ORDINAL_POSITION' => '7',
          'COLUMN_DEFAULT' => 'member',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'enum',
          'CHARACTER_MAXIMUM_LENGTH' => '9',
          'CHARACTER_OCTET_LENGTH' => '27',
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8',
          'COLLATION_NAME' => 'utf8_unicode_ci',
          'COLUMN_TYPE' => 'enum(\'banned\',\'member\',\'admin\',\'staff\',\'superuser\',\'\')',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
        'title' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'user',
          'COLUMN_NAME' => 'title',
          'ORDINAL_POSITION' => '8',
          'COLUMN_DEFAULT' => 'newbie',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => '64',
          'CHARACTER_OCTET_LENGTH' => '192',
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8',
          'COLLATION_NAME' => 'utf8_unicode_ci',
          'COLUMN_TYPE' => 'varchar(64)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
        'avatar' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'user',
          'COLUMN_NAME' => 'avatar',
          'ORDINAL_POSITION' => '9',
          'COLUMN_DEFAULT' => 'http://dmvgs.co.uk/uploads/default-avatar.jpg',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => '255',
          'CHARACTER_OCTET_LENGTH' => '765',
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8',
          'COLLATION_NAME' => 'utf8_unicode_ci',
          'COLUMN_TYPE' => 'varchar(255)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
        'post_signature' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'user',
          'COLUMN_NAME' => 'post_signature',
          'ORDINAL_POSITION' => '10',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'text',
          'CHARACTER_MAXIMUM_LENGTH' => '65535',
          'CHARACTER_OCTET_LENGTH' => '65535',
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8',
          'COLLATION_NAME' => 'utf8_unicode_ci',
          'COLUMN_TYPE' => 'text',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
        'state' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'user',
          'COLUMN_NAME' => 'state',
          'ORDINAL_POSITION' => '11',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'smallint',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '5',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'smallint(5) unsigned',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
      ),
      'indexes' => 
      array (
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 'user',
            'Non_unique' => '0',
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => '1',
            'Column_name' => 'user_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'username' => 
        array (
          1 => 
          array (
            'Table' => 'user',
            'Non_unique' => '0',
            'Key_name' => 'username',
            'Seq_in_index' => '1',
            'Column_name' => 'username',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => 'YES',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'email' => 
        array (
          1 => 
          array (
            'Table' => 'user',
            'Non_unique' => '0',
            'Key_name' => 'email',
            'Seq_in_index' => '1',
            'Column_name' => 'email',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => 'YES',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => NULL,
    ),
    'user_uuid' => 
    array (
      'table' => 
      array (
        'table_name' => 'user_uuid',
        'engine' => 'InnoDB',
        'table_comment' => '',
        'table_collation' => 'utf8_unicode_ci',
        'character_set_name' => 'utf8',
      ),
      'columns' => 
      array (
        'user_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'user_uuid',
          'COLUMN_NAME' => 'user_id',
          'ORDINAL_POSITION' => '1',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '10',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
        'uuid' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'user_uuid',
          'COLUMN_NAME' => 'uuid',
          'ORDINAL_POSITION' => '2',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'char',
          'CHARACTER_MAXIMUM_LENGTH' => '36',
          'CHARACTER_OCTET_LENGTH' => '108',
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8',
          'COLLATION_NAME' => 'utf8_unicode_ci',
          'COLUMN_TYPE' => 'char(36)',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
        'type' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_SCHEMA' => 'dmvgs_forum',
          'TABLE_NAME' => 'user_uuid',
          'COLUMN_NAME' => 'type',
          'ORDINAL_POSITION' => '3',
          'COLUMN_DEFAULT' => 'reset_password',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'enum',
          'CHARACTER_MAXIMUM_LENGTH' => '14',
          'CHARACTER_OCTET_LENGTH' => '42',
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8',
          'COLLATION_NAME' => 'utf8_unicode_ci',
          'COLUMN_TYPE' => 'enum(\'reset_password\')',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
        ),
      ),
      'indexes' => 
      array (
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 'user_uuid',
            'Non_unique' => '0',
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => '1',
            'Column_name' => 'user_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
          2 => 
          array (
            'Table' => 'user_uuid',
            'Non_unique' => '0',
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => '2',
            'Column_name' => 'uuid',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
        'user_uuid_ibfk_1' => 
        array (
          'TABLE_NAME' => 'user_uuid',
          'COLUMN_NAME' => 'user_id',
          'CONSTRAINT_NAME' => 'user_uuid_ibfk_1',
          'REFERENCED_TABLE_NAME' => 'user',
          'REFERENCED_COLUMN_NAME' => 'user_id',
          'UPDATE_RULE' => 'RESTRICT',
          'DELETE_RULE' => 'RESTRICT',
        ),
      ),
    ),
  ),
);