<?php
	$title = "Committee";
	$this->headTitle($title);
?>
<div class="">
	<h3 class="year_committee">Current committee (2014-2015)</h3>
	<div id="14-15panel" class="year_committee">
		<div>
		<ul>
			<li>Ryan Wilson (Chairman)</li>
			<li>Callum Varle (Technical Officer)</li>
			<li>Imogen Perkins (Health and Safety Officer)</li>
			<li>Gethin Watkins (Social Officer)</li>
			<li>Alex (Gaming Officer)</li>
		</ul>
		<p>The above people are your go-to team this year! They will be working to maintain the success of the previous committee whilst bringing in their own agendas, socials, competitions and  personal touch to the society. If you have any problems or questions just send them a message on here, facebook or chat to them in person, they will be happy to help!</p>
	</div>
	<div class="pagebreak"></div>
	<h3 class="year_committee">Previous years</h3>
	<div id="13-14panel" class="year_committee">
		<h2>Committee (2013-2014)</h2>
		<ul>
			<li>Lauren Jepson (Chairman)</li>
			<li>Josh Martin (Technical Officer)</li>
			<li>Max Rushin (Gaming Officer)</li>
			<li>Olivia Davy (Social Officer)</li>
			<li>James Bradley (Health and Safety)</li>
		</ul>
		<img src="http://dmvgs.co.uk/content/img/pages/home/gallery/1.jpg" alt="committee 13-14"/>
		<p>This committee brought in a lot of changes to the society, including it's name (previously Demon Gamers), logo and sponsor! During this year paying members rose by 300-400%, meaning the society had almost 100 paying members for the first time ever. The Technical Officer of this year, Josh Martin, created the website you're now visiting from scratch. Cheers Josh!</p>
	</div>
	<div class="pagebreak"></div>
	<div id="12-13panel" class="year_committee">
		<h2>Committee (2012-2013)</h2>
		<ul>
			<li>Beejay Guy (Chairman)</li>
			<li>Lauren Jepson (Social Officer)</li>
			<li>Aaron Roberts (Console Gaming Officer)</li>
			<li>Harry Semple (PC Gaming Officer)</li>
			<li>David Croft (Technical Officer)</li>
		</ul>
	</div>
	<div class="pagebreak"></div>
	<div id="11-12panel" class="year_committee">
		<h2>Committee (2011-2012)</h2>
		<ul>
			<li>Joanna Lanham (Chairman)</li>
			<li>Lewis Woodrow (Social Officer)</li>
			<li>Laurie Tutton (Technical Officer)</li>
		</ul>
	</div>
</div>
