<?php
	$title = "Welcome";
	$this->headTitle($title);
?>
<div id="subwrapper">
	<div id="mainWelcome">
		<p>Welcome! We're DMU's Video Gaming Society, here to fulfil all your gaming needs! You've found our website. Please use the website and society as a place to talk about games, find like-minded people and, above all, make friends, have fun!</p>
		<p>Please refer to the <a href="/site/about">FAQ</a> in the comments if you have any general questions! If you cannot find an answer to your question please leave a message on the <a href="/forum">Forums</a>. You can also find us on <a href="https://www.facebook.com/groups/700697783277417/">Facebook</a>. Feel free to post on the forums/facebook group introducing yourself, we love meeting new people and welcome any new members.</p>
	</div>
	
	<div id="gallery"></div>
</div>


<link href="/content/css/home.css" media="screen" rel="stylesheet" type="text/css">
<script type="text/javascript" src="<?= $this->basePath() ?>/scripts/pages/home.js"></script>